#服务器端口
server:
  port: 8082
  tomcat:
    threads:
      min-spare: 5
      max: 30
    accept-count: 60



spring:
  profiles:
    active: dev
#    开启 接受  循环依赖, 子模块之间可能出现循环依赖
  main:
    allow-circular-references: true

  datasource:
    druid:
      driver-class-name: ${wenxun.datasource.driver-class-name}
      url: jdbc:mysql://${wenxun.datasource.host}:${wenxun.datasource.port}/${wenxun.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${wenxun.datasource.username}
      password: ${wenxun.datasource.password}
      initial-size: 5
      min-idle: 10
      max-active: 20
    type:  com.alibaba.druid.pool.DruidDataSource

  redis:
    host: ${wenxun.redis.host}
    port: ${wenxun.redis.port}
    password: ${wenxun.redis.password}
    database: ${wenxun.redis.database}


#任务提交的线程池
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 10

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:  com.wenxun.entity
  configuration:
#    驼峰命名
    map-underscore-to-camel-case: true
rocketmq:
  name-server: localhost:9876
  producer:
    group: seckill_producer

frontend:
  web:
    path: ${wenxun.frontend.web.path}


logging:
  level:
   com:
   wenxun:
    mapper: debug # debug 可以打印mysql命令
    service: info
    controller: info

jwt:
  secretKey: store_kill
  ttl: 7200000
  frontEndTokenName: token