wenxun:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: loalhost
    port: 3306
    database: seckill
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  rabbitmq:
    host: localhost
    port:
