wenxun:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: seckill
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  rocketmq:
    name-server: localhost:9876
    producer:
      group: seckill_producer



  frontend:
    web:
      path: http://127.0.0.1:5500