package com.wenxun.mapper;

import com.wenxun.entity.ItemStockLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface ItemStockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated
     */
    int insert(ItemStockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated
     */
    ItemStockLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated
     */
    List<ItemStockLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemStockLog record);

    /**
     * 更新库存流水状态
     * @param id
     * @param status
     * @return
     */
    int updateStatusById(String id, Integer status);
}