package com.wenxun.mapper;

import com.wenxun.entity.Promotion;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated
     */
    int insert(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     * @param itemId
     * @mbg.generated
     */
    Promotion selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated
     */
    List<Promotion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Promotion record);
}